### ISSUE TITLE
WriteCharacteristic() blocks indefinitely after disconnect

### ISSUE THREAD

**Issue by alexozer** [alexozer/jankcopter#1]
Calling `periph.WriteCharacteristic(characteristic, msg, true)` blocks indefinitely after the bluetooth connection is closed. Since `WriteCharacteristic()` does this instead of returning an error, we cannot know for sure when to stop the goroutine from writing and thus cannot restart the connection without restarting the entire client.

It should also be noted that this only occurs if a message is send before an attempted reconnection.

**Comment by alexozer** [comment]
Could potentially switch to go-bluetooth, see #3

**Comment by jreynojustin** [comment]
Did you try periph.WriteCharacteristicWhenBluetoothConnected(yes, characteristic, msg, true)?

**Comment by alexozer** [comment]
@jreynojustin I thought about calling that, but it seemed dangerous. Do you think it would work?

**Comment by alexozer** [comment]
Architecture switched to radio from bluetooth
